FROM openjdk:11.0.4-jdk-slim

RUN mkdir /usr/share/man/man1\
    && apt-get -q update --yes \
    && apt-get -q install --yes --no-install-recommends git maven ant curl gpg \
    && rm -rf /var/lib/apt/lists/*

RUN echo ============== \
    && java -version \
    && javac -version \
    && mvn -version \
    && ant -version \
    && git --version \
    && gpg --version \
    && curl --version \
    && date

WORKDIR /root

ENTRYPOINT /bin/bash
